[log]
    path    = "gogo.log"
    level   = "debug"

[server]
    username    = "admin"
    password    = "verytopsecret"

    [server.http]
        host    = "localhost"
        port    = 8181

    [server.sock]
        file    = "/var/run/gogo.sock"
        chmod   = "0777"
        chown   = "root:root"

[task]
    environment = { foo = "Bar" }
    autostart = true
    instances = 1
    priority = 999
    settle = 3
    retries = 5
    delay = 5
    stopsignal = "TERM"
    stoptimeout = 5
    runuser = "root"
    rungroup = "root"
    subdir = "tasks"
